phorg improvements
  - target filename is the concatenation of date_time-serialno-first_10_chars_of_sha1sum-original_filename
  - improved logging
  - parallelization using GNU Parallel

diff --git a/bin/phorg b/bin/phorg
--- a/bin/phorg
+++ b/bin/phorg
@@ -8,21 +8,16 @@
 # --- Required tools
 # --- -------------------------------------------------------------------------
 type exiftool >/dev/null 2>&1 || { echo >&2 "Program exiftool is not installed. Aborting."; exit 1; }
+type sha1sum >/dev/null 2>&1 || { echo >&2 "Program sha1sum is not installed. Aborting."; exit 1; }
+type parallel >/dev/null 2>&1 || { echo >&2 "Program parallel is not installed. Aborting."; exit 1; }
+
+self=$(dirname $0)/$(basename ${0})
 
 : ${LOG_LEVEL:="INFO"}
 
 # load poor mans logger :)
 . $(dirname $0)/poor.mans.logger.sh
 
-
-cat << EOF
-       _               
-   ___| |_ ___ ___ ___ 
-  | . |   | . |  _| . |
-  |  _|_|_|___|_| |_  |
-  |_|             |___|
-
-EOF
 
 # --- -------------------------------------------------------------------------
 # --- Parameters with their default values
@@ -50,10 +45,22 @@ log_debug "param LOG_LEVEL='${LOG_LEVEL}'"
 # --- Utility functions
 # --- -------------------------------------------------------------------------
 
+
+phorg_logo(){
+cat << EOF
+       _               
+   ___| |_ ___ ___ ___ 
+  | . |   | . |  _| . |
+  |  _|_|_|___|_| |_  |
+  |_|             |___|
+
+EOF
+}
+
 # reformat a line to fit into a max with of characters
 #   arg 1: text to reformat
 #   arg 2: maximum number of characters (width, default is 80 characters)
-printFormatted(){
+printFormatted() {
   txt=${1}
 
   if [[ -z ${2} ]]; then
@@ -69,6 +76,7 @@ printFormatted(){
 }
 
 print_usage(){
+    phorg_logo
     echo "Usage: $(basename ${0}) [-o PARAMETER=VALUE ...]"
     echo ""
     printFormatted "-h | --help : display this help."
@@ -86,10 +94,13 @@ print_usage(){
     printFormatted "PHOTO_FILES_PATTERN=<filename pattern> : Filename pattern to match input photo files (DEFAULT is 'DSC_[0-9][0-9][0-9][0-9].NEF')"
     printFormatted "VIDEO_FILES_PATTERN=<filename pattern> : Filename pattern to match input video files (DEFAULT is 'DSC_[0-9][0-9][0-9][0-9].MOV')"
     printFormatted "LOG_LEVEL=<ALL | DEBUG | WARN | INFO | ERROR | OFF>: Specify the logging level (DEFAULT is ERROR)."
+
+    echo ""
+    echo "this script is located at: ${self}"
 }
 
 
-reorganize(){
+reorganize() {
 
     reorganize_mode=$1
     filename=$2
@@ -115,29 +126,42 @@ reorganize(){
     filename_ext="${filename_base##*.}";
 
     serial_no=$(exiftool  -SerialNumber ${filename} | cut -d : -f 2 | tr -d '[:space:]')
-    parent_dir=$(dirname ${c_filename} | xargs basename)
-    parent_dir="${parent_dir// /_}"
-    
-    if [[ "${parent_dir}" != "." ]]; then
-        new_filename="${parent_dir}-${c_fdt}-${serial_no}-${filename_raw}.${filename_ext}"
-    else
-        new_filename="${c_fdt}-${serial_no}-${filename_raw}.${filename_ext}"
+    if [[ ! -z "${serial_no}" ]]; then
+        serial_no="-${serial_no}"
     fi
+    sha1sum=$(sha1sum "${filename}" | cut -d ' ' -f 1)
+    short_sha1sum=$(echo "${sha1sum}" | cut -c 1-10)
+    
 
-
+    new_filename="${c_fdt}${serial_no}-${short_sha1sum}-${filename_raw}.${filename_ext}"
     target_filepath="$OUTPUT_DIR/$c_date_y/$c_date_m/$new_filename"
+
+    if [[ -f "${target_filepath}" ]]; then
+        target_sha1sum=$(sha1sum "${target_filepath}" | cut -d ' ' -f 1)
+        if [[ "${target_sha1sum}" == "${sha1sum}" ]]; then
+            log_warn "File '${target_filepath}' already exists, skipping '${filename}'"
+            return 0
+        else
+            unix_timestamp=$(date +%s)
+            alt_new_filename="${c_fdt}${serial_no}-${short_sha1sum}-${unix_timestamp}-${filename_raw}.${filename_ext}"
+            alt_target_filepath="$OUTPUT_DIR/$c_date_y/$c_date_m/$alt_new_filename"
+            
+            log_warn "File '${target_filepath}' already exists, but has different content, renaming to '${alt_target_filepath}'"
+            target_filepath="${alt_target_filepath}"
+        fi
+    fi
     
     case ${reorganize_mode} in
         0)
-            log_info "[DRY] Copying/Moving '$filename' to '${target_filepath}'"
+            log_info "[DRY] Copying/Moving '${filename}' to '${target_filepath}'"
         ;;
         1)
-            log_info "Moving '$filename' to '${target_filepath}'"
+            log_info "Moving '${filename}' to '${target_filepath}'"
             mv "$filename" "${target_filepath}"
         ;;
         2)
-            log_info "Copying '$filename' to '${target_filepath}'"
-            cp "$filename" "${target_filepath}"
+            log_info "Copying '${filename}' to '${target_filepath}'"
+            cp "${filename}" "${target_filepath}"
         ;;
         *)
             log_info "Unknown mode '${reorganize_mode}'"
@@ -145,6 +169,62 @@ reorganize(){
         ;;
     esac
 }
+
+process_video_file() {
+    local c_filename="$1"
+   
+    log_info "Processing file '${c_filename}'"
+    c_date=$($STAT -f %Sm -t %Y-%m "${c_filename}")
+    c_date_exit_code=$?
+
+    c_fdt=$($STAT -f %Sm -t ${PREFIX_DT_PATTERN} "${c_filename}")
+    c_fdt_exit_code=$?
+
+    exit_code=$([[ ${c_date_exit_code} -eq 0 && ${c_fdt_exit_code} -eq 0 ]] && echo 0 || echo 1)
+
+    if [[ $exit_code -eq 0 ]]; then
+        reorganize "$_mode" "$c_filename" "$c_date" "$c_fdt"
+    else
+        log_error "Error getting file date for '${c_filename}'"
+        exit $exit_code
+    fi
+}
+
+process_image_file() {
+    local c_filename="$1"
+
+    log_info "Processing file '${c_filename}'"
+    # Get the creation date from the media format meta data. If not found,
+    # use the file modified time.    
+    c_date=$(exiftool "${c_filename}" -CreateDate -d "%Y-%m" | cut -d : -f 2 | tr -d '[:space:]')
+    c_date_exit_code=$?
+
+    c_fdt=$(exiftool "${c_filename}" -CreateDate -d "${PREFIX_DT_PATTERN}" | cut -d : -f 2 | tr -d '[:space:]')
+    c_fdt_exit_code=$?
+
+    
+
+    if [[ "$c_date" == "0000" || "$c_date" == "" ]]; then
+        # The arguments for stat are specific to FreeNAS and are not very
+        # portable. This could break at any time. exiftool has
+        # FileModifyDate, try that some time.
+        c_date=$($STAT -f %Sm -t %Y-%m "${c_filename}")
+        c_date_exit_code=$?
+
+        c_fdt=$($STAT -f %Sm -t ${PREFIX_DT_PATTERN} "${c_filename}")
+        c_fdt_exit_code=$?
+    fi
+
+    exit_code=$([[ ${c_date_exit_code} -eq 0 && ${c_fdt_exit_code} -eq 0 ]] && echo 0 || echo 1)
+
+    if [[ $exit_code -eq 0 ]]; then
+        reorganize "$_mode" "${c_filename}" "$c_date" "$c_fdt"
+    else
+        log_error "Error getting file date for '${c_filename}'"
+        exit $exit_code
+    fi
+}
+
 
 # --- -------------------------------------------------------------------------
 # --- Main
@@ -158,6 +238,7 @@ fi
 
 
 # Parse arguments
+single_file_logging=0
 while [[ $# -gt 0 ]]
 do
     key="${1}"
@@ -172,7 +253,16 @@ do
         print_usage
         exit 0
         ;;
-
+    -F|--image-file)
+        image_file="${2}"
+        shift 2 # parse argument and value
+        single_file_logging=1
+    ;;
+    -V|--video-file)
+        video_file="${2}"
+        shift 2 # parse argument and value
+        single_file_logging=1
+    ;;
     *)  # unknown option
         log_error "Error unknown argument '${1}'"
         exit 1
@@ -187,7 +277,9 @@ _mode=0
 
 case ${MODE} in
     dry)
-        log_info "Dry run, will only print log messages!"
+        if [[ $single_file_logging -eq 0 ]]; then
+            log_info "Dry run, will only print log messages!"
+        fi
         _mode=0
     ;;
     move)
@@ -204,42 +296,26 @@ case ${MODE} in
     ;;
 esac
 
-# Re-organize video files
-log_info "Step 1/2: Re-organizing video files..."
 
-for c_filename in $(find ${INPUT_DIR} -type f -name "${VIDEO_FILES_PATTERN}")
-do
-  c_date=$($STAT -f %Sm -t %Y-%m "${c_filename}")
-  c_fdt=$($STAT -f %Sm -t ${PREFIX_DT_PATTERN} "${c_filename}")
+if [[ ${image_file} != "" ]]; then
+    log_debug "Processing single image file '${image_file}'"
+    process_image_file "${image_file}"
+elif [[ ${video_file} != "" ]]; then
+    log_debug "Processing single video file '${video_file}'"
+    process_video_file "${video_file}"
+else
+    phorg_logo
+    log_debug "Processing all files in '${INPUT_DIR}'"
 
-  exit_code=$? 
+    log_info "Step 1/2: Re-organizing video files..."
+    find ${INPUT_DIR} -type f -name "${VIDEO_FILES_PATTERN}" -print | \
+        parallel --load 75% -j -1 --keep-order \
+        ${self} --video-file {} -o MODE=${MODE} -o OUTPUT_DIR=${OUTPUT_DIR} -o STAT=${STAT} -o PREFIX_DT_PATTERN=${PREFIX_DT_PATTERN} -o PHOTO_FILES_PATTERN=${PHOTO_FILES_PATTERN} -o VIDEO_FILES_PATTERN=${VIDEO_FILES_PATTERN}
 
-  if [[ $? -eq 0 ]]; then
-    reorganize "$_mode" "$c_filename" "$c_date" "$c_fdt"
-  fi
-done
 
-# Re-organize photo files
-log_info "Step 2/2: Re-organizing photo files..."
+    log_info "Step 2/2: Re-organizing photo files..."
+    find ${INPUT_DIR} -type f -name "${PHOTO_FILES_PATTERN}" -print | \
+        parallel --load 75% -j -1 --keep-order \
+        ${self} --image-file {} -o MODE=${MODE} -o OUTPUT_DIR=${OUTPUT_DIR} -o STAT=${STAT} -o PREFIX_DT_PATTERN=${PREFIX_DT_PATTERN} -o PHOTO_FILES_PATTERN=${PHOTO_FILES_PATTERN} -o VIDEO_FILES_PATTERN=${VIDEO_FILES_PATTERN}
 
-for c_filename in $(find ${INPUT_DIR} -type f -name "${PHOTO_FILES_PATTERN}")
-do
-    # Get the creation date from the media format meta data. If not found,
-    # use the file modified time.    
-    c_date=$(exiftool "${c_filename}" -CreateDate -d "%Y-%m" | cut -d : -f 2 | tr -d '[:space:]')
-    c_fdt=$(exiftool "${c_filename}" -CreateDate -d "${PREFIX_DT_PATTERN}" | cut -d : -f 2 | tr -d '[:space:]')
-
-    if [[ "$c_date" == "0000" || "$c_date" == "" ]]; then
-        # The arguments for stat are specific to FreeNAS and are not very
-        # portable. This could break at any time. exiftool has
-        # FileModifyDate, try that some time.
-        c_date=$($STAT -f %Sm -t %Y-%m "${c_filename}")
-        c_fdt=$($STAT -f %Sm -t ${PREFIX_DT_PATTERN} "${c_filename}")
-    fi
-
-    exit_code=$? 
-
-    if [[ $? -eq 0 ]]; then
-        reorganize "$_mode" "${c_filename}" "$c_date" "$c_fdt"
-    fi
-done
+fi
